### ISSUE TITLE
Decouple `MacheteClient` and `GitContext` API from command-line options

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#161]
Imagine someone wants to call a method on `MacheteClient` programatically... currently to create an instance on `MacheteClient`, they need to pass the entire `CommandLineContext` (`CommandLineOptions`?) object, even though their use case has nothing to do with CLI.

Let's consider decoupling `CommandLineContext` from what's passed to API methods. `MacheteClient` should know nothing about `CommandLineContext`; probably each method should only receive the options that are relevant to its execution, and the naming of this options doesn't need to exactly follow the naming of command-line options.

**Comment by BartoszSiwinski** [comment]
How about instead of decoupling it, we could make it in such way that `MacheteClient` itself is creating instance of `GitContext` and `CommandLineOptions`?

I would propose also to reconsider what is called in the `launch` method in `cli.py`. We could `get a parser` there, `parse the arguments` using it and than `pass the parsed arguments` as only input parameter to `MacheteClient.__init__()`. After that everything else would happen inside `MacheteClient` including recognizing what cmd was called.

**Comment by PawelLipski** [comment]
Hmmm IIUC that problem then would be that `MacheteClient` would be again strongly coupled to CLI, right? 🤔 for the sake of making the graph of dependencies less dense/easier to grasp, my idea was to make `MacheteClient` as oblivious to the existence of command line as possible

**Comment by PawelLipski** [comment]
See e.g. places where `cli_options` are set before calling method `add` just so that the behavior of `add` is changed (`git_machete/client.py:1708`)... this should instead be done by passing an argument to `add`
