### ISSUE TITLE
`--by=<TAB>` prompts file names in Bash, should prompt nothing

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#526]
![image](https://user-images.githubusercontent.com/3383210/168877065-45a2b700-a379-4b89-8550-88f06f7c49c6.png)

Let's also check if other shells have the same bug

**Comment by amalota** [comment]
@PawelLipski 

**ZSH (oh-my-zsh)** -> works OK

**BASH** -> completion doesn't work (trying to fix it) but pressing <TAB> twice after `any_command_even_non_existent_one `  always prompts file names, maybe that's what happened in your case too, can You check?

-   update: after some time i finally managed to get bash git machete completion to work, (i'll create new PR that will 
update the completion' README because its incomplete for macos) and was bale to reproduce the mentioned prompt bug

**FISH** -> works OK although doesn't prompt anything after `git machete github checkout-prs` until character `-` is provided, then correctly prompts `--all `,  `--by` and `--mine`

**Comment by amalota** [comment]
Update: 
Looks like `git machete discover --checked-out-since=` also prompts file names

**Comment by PawelLipski** [comment]
Huh okay so is some check on Linux/bash needed on my part?

`git machete discover --checked-out-since=` on Linux&bash indeed prompts filenames

In general, I suppose setting `COMPREPLY=('')` should suffice (as done in a couple places already)
